name: Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:
  workflow_dispatch:

jobs:
  test_windows_powershell:
    name: Windows PowerShell
    runs-on: windows-latest

    steps:
      - name: Checkout Bucket
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          path: my_bucket

      - name: Checkout Scoop Core
        uses: actions/checkout@v4
        with:
          repository: ScoopInstaller/Scoop
          path: scoop_core

      - name: Run Bucket Tests
        shell: powershell
        run: |
          $ErrorActionPreference = 'Stop'
          $env:SCOOP_HOME = (Convert-Path '.\scoop_core')
          .\my_bucket\bin\test.ps1


  test_pwsh:
    name: PowerShell (pwsh)
    runs-on: windows-latest

    steps:
      - name: Checkout Bucket
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          path: my_bucket

      - name: Checkout Scoop Core
        uses: actions/checkout@v4
        with:
          repository: ScoopInstaller/Scoop
          path: scoop_core

      - name: Run Bucket Tests
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          $env:SCOOP_HOME = (Convert-Path '.\scoop_core')
          .\my_bucket\bin\test.ps1
